# Generated by Django 4.2.7 on 2023-12-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pictures',
            field=models.ImageField(default='/scrhyme/media/user_image/default_icon.png', upload_to='user_image/'),
        ),
    ]
