# Generated by Django 4.2.7 on 2023-12-06 16:18

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='song',
            field=models.FileField(default='', upload_to='songs/', validators=[main.validators.validate_is_audio]),
        ),
    ]
