# Generated by Django 4.2.7 on 2023-12-08 17:12

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_songs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='song',
            field=models.FileField(default='', upload_to='mvp1/scrhyme/media/songs/', validators=[main.validators.validate_is_audio]),
        ),
    ]
