# Generated by Django 4.2.7 on 2023-12-08 17:34

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_songs_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='song',
            field=models.FileField(upload_to='uploaded_songs', validators=[main.validators.validate_is_audio]),
        ),
    ]
