# Generated by Django 4.2.7 on 2023-12-11 03:29

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_songs_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='username',
            field=models.CharField(max_length=30, verbose_name=accounts.models.CustomUser),
        ),
    ]
