# Generated by Django 4.2.7 on 2023-12-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_songs_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='songtitle',
            field=models.CharField(max_length=30, verbose_name='Song Title'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='username',
            field=models.CharField(max_length=30, verbose_name='Artist Name'),
        ),
    ]
