# Generated by Django 4.2.7 on 2023-12-12 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_likeforpost_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
    ]
