# Generated by Django 4.2.7 on 2023-12-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_likeforpost_target_remove_likeforpost_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
    ]
