# Generated by Django 4.2.7 on 2023-12-12 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_songs_like_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='like_num',
        ),
    ]
