# Generated by Django 4.2.7 on 2023-12-13 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_likes_likes_songs_user_unique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
