# Generated by Django 4.2.7 on 2023-12-30 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_songs_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Artist Name')),
                ('vocal', models.FileField(upload_to='uploaded_vocals', validators=[main.validators.validate_is_audio])),
                ('request', models.TextField(max_length=256, verbose_name='request')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='posted at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.RemoveField(
            model_name='songs',
            name='profile_picture',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
